<?php

namespace Modules\Geo\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Geo\Models\Country;
use Illuminate\Support\Str;

class CountriesSeed extends Seeder
{
    /**
     * Run the database seeds - All 195+ Countries
     */
    public function run(): void
    {
        $countries = [
            ['iso' => 'AF', 'emoji' => '🇦🇫', 'names' => [['locale' => 'en', 'value' => 'Afghanistan'], ['locale' => 'ar', 'value' => 'أفغانستان']]],
            ['iso' => 'AX', 'emoji' => '🇦🇽', 'names' => [['locale' => 'en', 'value' => 'Åland Islands'], ['locale' => 'ar', 'value' => 'جزر آلاند']]],
            ['iso' => 'AL', 'emoji' => '🇦🇱', 'names' => [['locale' => 'en', 'value' => 'Albania'], ['locale' => 'ar', 'value' => 'ألبانيا']]],
            ['iso' => 'DZ', 'emoji' => '🇩🇿', 'names' => [['locale' => 'en', 'value' => 'Algeria'], ['locale' => 'ar', 'value' => 'الجزائر']]],
            ['iso' => 'AS', 'emoji' => '🇦🇸', 'names' => [['locale' => 'en', 'value' => 'American Samoa'], ['locale' => 'ar', 'value' => 'ساموا الأمريكية']]],
            ['iso' => 'AD', 'emoji' => '🇦🇩', 'names' => [['locale' => 'en', 'value' => 'Andorra'], ['locale' => 'ar', 'value' => 'أندورا']]],
            ['iso' => 'AO', 'emoji' => '🇦🇴', 'names' => [['locale' => 'en', 'value' => 'Angola'], ['locale' => 'ar', 'value' => 'أنغولا']]],
            ['iso' => 'AI', 'emoji' => '🇦🇮', 'names' => [['locale' => 'en', 'value' => 'Anguilla'], ['locale' => 'ar', 'value' => 'أنغويلا']]],
            ['iso' => 'AQ', 'emoji' => '🇦🇶', 'names' => [['locale' => 'en', 'value' => 'Antarctica'], ['locale' => 'ar', 'value' => 'القارة القطبية الجنوبية']]],
            ['iso' => 'AG', 'emoji' => '🇦🇬', 'names' => [['locale' => 'en', 'value' => 'Antigua and Barbuda'], ['locale' => 'ar', 'value' => 'أنتيغوا وبربودا']]],
            ['iso' => 'AR', 'emoji' => '🇦🇷', 'names' => [['locale' => 'en', 'value' => 'Argentina'], ['locale' => 'ar', 'value' => 'الأرجنتين']]],
            ['iso' => 'AM', 'emoji' => '🇦🇲', 'names' => [['locale' => 'en', 'value' => 'Armenia'], ['locale' => 'ar', 'value' => 'أرمينيا']]],
            ['iso' => 'AW', 'emoji' => '🇦🇼', 'names' => [['locale' => 'en', 'value' => 'Aruba'], ['locale' => 'ar', 'value' => 'أروبا']]],
            ['iso' => 'AU', 'emoji' => '🇦🇺', 'names' => [['locale' => 'en', 'value' => 'Australia'], ['locale' => 'ar', 'value' => 'أستراليا']]],
            ['iso' => 'AT', 'emoji' => '🇦🇹', 'names' => [['locale' => 'en', 'value' => 'Austria'], ['locale' => 'ar', 'value' => 'النمسا']]],
            ['iso' => 'AZ', 'emoji' => '🇦🇿', 'names' => [['locale' => 'en', 'value' => 'Azerbaijan'], ['locale' => 'ar', 'value' => 'أذربيجان']]],
            ['iso' => 'BS', 'emoji' => '🇧🇸', 'names' => [['locale' => 'en', 'value' => 'Bahamas'], ['locale' => 'ar', 'value' => 'الباهاما']]],
            ['iso' => 'BH', 'emoji' => '🇧🇭', 'names' => [['locale' => 'en', 'value' => 'Bahrain'], ['locale' => 'ar', 'value' => 'البحرين']]],
            ['iso' => 'BD', 'emoji' => '🇧🇩', 'names' => [['locale' => 'en', 'value' => 'Bangladesh'], ['locale' => 'ar', 'value' => 'بنغلاديش']]],
            ['iso' => 'BB', 'emoji' => '🇧🇧', 'names' => [['locale' => 'en', 'value' => 'Barbados'], ['locale' => 'ar', 'value' => 'بربادوس']]],
            ['iso' => 'BY', 'emoji' => '🇧🇾', 'names' => [['locale' => 'en', 'value' => 'Belarus'], ['locale' => 'ar', 'value' => 'بيلاروسيا']]],
            ['iso' => 'BE', 'emoji' => '🇧🇪', 'names' => [['locale' => 'en', 'value' => 'Belgium'], ['locale' => 'ar', 'value' => 'بلجيكا']]],
            ['iso' => 'BZ', 'emoji' => '🇧🇿', 'names' => [['locale' => 'en', 'value' => 'Belize'], ['locale' => 'ar', 'value' => 'بليز']]],
            ['iso' => 'BJ', 'emoji' => '🇧🇯', 'names' => [['locale' => 'en', 'value' => 'Benin'], ['locale' => 'ar', 'value' => 'بنين']]],
            ['iso' => 'BM', 'emoji' => '🇧🇲', 'names' => [['locale' => 'en', 'value' => 'Bermuda'], ['locale' => 'ar', 'value' => 'برمودا']]],
            ['iso' => 'BT', 'emoji' => '🇧🇹', 'names' => [['locale' => 'en', 'value' => 'Bhutan'], ['locale' => 'ar', 'value' => 'بوتان']]],
            ['iso' => 'BO', 'emoji' => '🇧��', 'names' => [['locale' => 'en', 'value' => 'Bolivia'], ['locale' => 'ar', 'value' => 'بوليفيا']]],
            ['iso' => 'BA', 'emoji' => '🇧🇦', 'names' => [['locale' => 'en', 'value' => 'Bosnia and Herzegovina'], ['locale' => 'ar', 'value' => 'البوسنة والهرسك']]],
            ['iso' => 'BW', 'emoji' => '🇧🇼', 'names' => [['locale' => 'en', 'value' => 'Botswana'], ['locale' => 'ar', 'value' => 'بوتسوانا']]],
            ['iso' => 'BV', 'emoji' => '🇧🇻', 'names' => [['locale' => 'en', 'value' => 'Bouvet Island'], ['locale' => 'ar', 'value' => 'جزيرة بوفيه']]],
            ['iso' => 'BR', 'emoji' => '🇧🇷', 'names' => [['locale' => 'en', 'value' => 'Brazil'], ['locale' => 'ar', 'value' => 'البرازيل']]],
            ['iso' => 'IO', 'emoji' => '🇮🇴', 'names' => [['locale' => 'en', 'value' => 'British Indian Ocean Territory'], ['locale' => 'ar', 'value' => 'إقليم المحيط الهندي البريطاني']]],
            ['iso' => 'BN', 'emoji' => '🇧🇳', 'names' => [['locale' => 'en', 'value' => 'Brunei'], ['locale' => 'ar', 'value' => 'بروناي']]],
            ['iso' => 'BG', 'emoji' => '🇧🇬', 'names' => [['locale' => 'en', 'value' => 'Bulgaria'], ['locale' => 'ar', 'value' => 'بلغاريا']]],
            ['iso' => 'BF', 'emoji' => '🇧🇫', 'names' => [['locale' => 'en', 'value' => 'Burkina Faso'], ['locale' => 'ar', 'value' => 'بوركينا فاسو']]],
            ['iso' => 'BI', 'emoji' => '🇧🇮', 'names' => [['locale' => 'en', 'value' => 'Burundi'], ['locale' => 'ar', 'value' => 'بوروندي']]],
            ['iso' => 'KH', 'emoji' => '🇰🇭', 'names' => [['locale' => 'en', 'value' => 'Cambodia'], ['locale' => 'ar', 'value' => 'كمبوديا']]],
            ['iso' => 'CM', 'emoji' => '🇨🇲', 'names' => [['locale' => 'en', 'value' => 'Cameroon'], ['locale' => 'ar', 'value' => 'الكاميرون']]],
            ['iso' => 'CA', 'emoji' => '🇨🇦', 'names' => [['locale' => 'en', 'value' => 'Canada'], ['locale' => 'ar', 'value' => 'كندا']]],
            ['iso' => 'CV', 'emoji' => '🇨🇻', 'names' => [['locale' => 'en', 'value' => 'Cape Verde'], ['locale' => 'ar', 'value' => 'الرأس الأخضر']]],
            ['iso' => 'KY', 'emoji' => '🇰🇾', 'names' => [['locale' => 'en', 'value' => 'Cayman Islands'], ['locale' => 'ar', 'value' => 'جزر كايمان']]],
            ['iso' => 'CF', 'emoji' => '🇨🇫', 'names' => [['locale' => 'en', 'value' => 'Central African Republic'], ['locale' => 'ar', 'value' => 'جمهورية أفريقيا الوسطى']]],
            ['iso' => 'TD', 'emoji' => '🇹🇩', 'names' => [['locale' => 'en', 'value' => 'Chad'], ['locale' => 'ar', 'value' => 'تشاد']]],
            ['iso' => 'CL', 'emoji' => '🇨🇱', 'names' => [['locale' => 'en', 'value' => 'Chile'], ['locale' => 'ar', 'value' => 'تشيلي']]],
            ['iso' => 'CN', 'emoji' => '🇨🇳', 'names' => [['locale' => 'en', 'value' => 'China'], ['locale' => 'ar', 'value' => 'الصين']]],
            ['iso' => 'CX', 'emoji' => '🇨🇽', 'names' => [['locale' => 'en', 'value' => 'Christmas Island'], ['locale' => 'ar', 'value' => 'جزيرة عيد الميلاد']]],
            ['iso' => 'CC', 'emoji' => '🇨🇨', 'names' => [['locale' => 'en', 'value' => 'Cocos Islands'], ['locale' => 'ar', 'value' => 'جزر كوكوس']]],
            ['iso' => 'CO', 'emoji' => '🇨🇴', 'names' => [['locale' => 'en', 'value' => 'Colombia'], ['locale' => 'ar', 'value' => 'كولومبيا']]],
            ['iso' => 'KM', 'emoji' => '🇰🇲', 'names' => [['locale' => 'en', 'value' => 'Comoros'], ['locale' => 'ar', 'value' => 'جزر القمر']]],
            ['iso' => 'CG', 'emoji' => '🇨🇬', 'names' => [['locale' => 'en', 'value' => 'Congo'], ['locale' => 'ar', 'value' => 'الكونغو']]],
            ['iso' => 'CD', 'emoji' => '🇨🇩', 'names' => [['locale' => 'en', 'value' => 'Democratic Republic of the Congo'], ['locale' => 'ar', 'value' => 'جمهورية الكونغو الديمقراطية']]],
            ['iso' => 'CK', 'emoji' => '🇨🇰', 'names' => [['locale' => 'en', 'value' => 'Cook Islands'], ['locale' => 'ar', 'value' => 'جزر كوك']]],
            ['iso' => 'CR', 'emoji' => '🇨🇷', 'names' => [['locale' => 'en', 'value' => 'Costa Rica'], ['locale' => 'ar', 'value' => 'كوستاريكا']]],
            ['iso' => 'HR', 'emoji' => '🇭🇷', 'names' => [['locale' => 'en', 'value' => 'Croatia'], ['locale' => 'ar', 'value' => 'كرواتيا']]],
            ['iso' => 'CU', 'emoji' => '🇨🇺', 'names' => [['locale' => 'en', 'value' => 'Cuba'], ['locale' => 'ar', 'value' => 'كوبا']]],
            ['iso' => 'CY', 'emoji' => '🇨🇾', 'names' => [['locale' => 'en', 'value' => 'Cyprus'], ['locale' => 'ar', 'value' => 'قبرص']]],
            ['iso' => 'CZ', 'emoji' => '🇨🇿', 'names' => [['locale' => 'en', 'value' => 'Czechia'], ['locale' => 'ar', 'value' => 'التشيك']]],
            ['iso' => 'DK', 'emoji' => '🇩🇰', 'names' => [['locale' => 'en', 'value' => 'Denmark'], ['locale' => 'ar', 'value' => 'الدنمارك']]],
            ['iso' => 'DJ', 'emoji' => '🇩🇯', 'names' => [['locale' => 'en', 'value' => 'Djibouti'], ['locale' => 'ar', 'value' => 'جيبوتي']]],
            ['iso' => 'DM', 'emoji' => '🇩🇲', 'names' => [['locale' => 'en', 'value' => 'Dominica'], ['locale' => 'ar', 'value' => 'دومينيكا']]],
            ['iso' => 'DO', 'emoji' => '🇩🇴', 'names' => [['locale' => 'en', 'value' => 'Dominican Republic'], ['locale' => 'ar', 'value' => 'جمهورية الدومينيكان']]],
            ['iso' => 'EC', 'emoji' => '🇪🇨', 'names' => [['locale' => 'en', 'value' => 'Ecuador'], ['locale' => 'ar', 'value' => 'الإكوادور']]],
            ['iso' => 'EG', 'emoji' => '🇪🇬', 'names' => [['locale' => 'en', 'value' => 'Egypt'], ['locale' => 'ar', 'value' => 'مصر']]],
            ['iso' => 'SV', 'emoji' => '🇸🇻', 'names' => [['locale' => 'en', 'value' => 'El Salvador'], ['locale' => 'ar', 'value' => 'السلفادور']]],
            ['iso' => 'GQ', 'emoji' => '🇬🇶', 'names' => [['locale' => 'en', 'value' => 'Equatorial Guinea'], ['locale' => 'ar', 'value' => 'غينيا الاستوائية']]],
            ['iso' => 'ER', 'emoji' => '🇪🇷', 'names' => [['locale' => 'en', 'value' => 'Eritrea'], ['locale' => 'ar', 'value' => 'إريتريا']]],
            ['iso' => 'EE', 'emoji' => '🇪🇪', 'names' => [['locale' => 'en', 'value' => 'Estonia'], ['locale' => 'ar', 'value' => 'إستونيا']]],
            ['iso' => 'ET', 'emoji' => '🇪🇹', 'names' => [['locale' => 'en', 'value' => 'Ethiopia'], ['locale' => 'ar', 'value' => 'إثيوبيا']]],
            ['iso' => 'FK', 'emoji' => '🇫🇰', 'names' => [['locale' => 'en', 'value' => 'Falkland Islands'], ['locale' => 'ar', 'value' => 'جزر فوكلاند']]],
            ['iso' => 'FO', 'emoji' => '🇫🇴', 'names' => [['locale' => 'en', 'value' => 'Faroe Islands'], ['locale' => 'ar', 'value' => 'جزر فارو']]],
            ['iso' => 'FJ', 'emoji' => '🇫🇯', 'names' => [['locale' => 'en', 'value' => 'Fiji'], ['locale' => 'ar', 'value' => 'فيجي']]],
            ['iso' => 'FI', 'emoji' => '🇫🇮', 'names' => [['locale' => 'en', 'value' => 'Finland'], ['locale' => 'ar', 'value' => 'فنلندا']]],
            ['iso' => 'FR', 'emoji' => '🇫🇷', 'names' => [['locale' => 'en', 'value' => 'France'], ['locale' => 'ar', 'value' => 'فرنسا']]],
            ['iso' => 'GF', 'emoji' => '🇬🇫', 'names' => [['locale' => 'en', 'value' => 'French Guiana'], ['locale' => 'ar', 'value' => 'غيانا الفرنسية']]],
            ['iso' => 'PF', 'emoji' => '🇵🇫', 'names' => [['locale' => 'en', 'value' => 'French Polynesia'], ['locale' => 'ar', 'value' => 'بولينيزيا الفرنسية']]],
            ['iso' => 'TF', 'emoji' => '🇹🇫', 'names' => [['locale' => 'en', 'value' => 'French Southern Territories'], ['locale' => 'ar', 'value' => 'الأراضي الفرنسية الجنوبية']]],
            ['iso' => 'GA', 'emoji' => '🇬🇦', 'names' => [['locale' => 'en', 'value' => 'Gabon'], ['locale' => 'ar', 'value' => 'الجابون']]],
            ['iso' => 'GM', 'emoji' => '🇬🇲', 'names' => [['locale' => 'en', 'value' => 'Gambia'], ['locale' => 'ar', 'value' => 'غامبيا']]],
            ['iso' => 'GE', 'emoji' => '🇬🇪', 'names' => [['locale' => 'en', 'value' => 'Georgia'], ['locale' => 'ar', 'value' => 'جورجيا']]],
            ['iso' => 'DE', 'emoji' => '🇩🇪', 'names' => [['locale' => 'en', 'value' => 'Germany'], ['locale' => 'ar', 'value' => 'ألمانيا']]],
            ['iso' => 'GH', 'emoji' => '🇬🇭', 'names' => [['locale' => 'en', 'value' => 'Ghana'], ['locale' => 'ar', 'value' => 'غانا']]],
            ['iso' => 'GI', 'emoji' => '🇬🇮', 'names' => [['locale' => 'en', 'value' => 'Gibraltar'], ['locale' => 'ar', 'value' => 'جبل طارق']]],
            ['iso' => 'GR', 'emoji' => '🇬🇷', 'names' => [['locale' => 'en', 'value' => 'Greece'], ['locale' => 'ar', 'value' => 'اليونان']]],
            ['iso' => 'GL', 'emoji' => '🇬🇱', 'names' => [['locale' => 'en', 'value' => 'Greenland'], ['locale' => 'ar', 'value' => 'جرينلاند']]],
            ['iso' => 'GD', 'emoji' => '🇬🇩', 'names' => [['locale' => 'en', 'value' => 'Grenada'], ['locale' => 'ar', 'value' => 'غرينادا']]],
            ['iso' => 'GP', 'emoji' => '🇬🇵', 'names' => [['locale' => 'en', 'value' => 'Guadeloupe'], ['locale' => 'ar', 'value' => 'جوادلوب']]],
            ['iso' => 'GU', 'emoji' => '🇬🇺', 'names' => [['locale' => 'en', 'value' => 'Guam'], ['locale' => 'ar', 'value' => 'جوام']]],
            ['iso' => 'GT', 'emoji' => '🇬🇹', 'names' => [['locale' => 'en', 'value' => 'Guatemala'], ['locale' => 'ar', 'value' => 'غواتيمالا']]],
            ['iso' => 'GG', 'emoji' => '🇬🇬', 'names' => [['locale' => 'en', 'value' => 'Guernsey'], ['locale' => 'ar', 'value' => 'جزيرة جيرنسي']]],
            ['iso' => 'GN', 'emoji' => '🇬🇳', 'names' => [['locale' => 'en', 'value' => 'Guinea'], ['locale' => 'ar', 'value' => 'غينيا']]],
            ['iso' => 'GW', 'emoji' => '🇬🇼', 'names' => [['locale' => 'en', 'value' => 'Guinea-Bissau'], ['locale' => 'ar', 'value' => 'غينيا بيساو']]],
            ['iso' => 'GY', 'emoji' => '🇬🇾', 'names' => [['locale' => 'en', 'value' => 'Guyana'], ['locale' => 'ar', 'value' => 'غيانا']]],
            ['iso' => 'HT', 'emoji' => '🇭🇹', 'names' => [['locale' => 'en', 'value' => 'Haiti'], ['locale' => 'ar', 'value' => 'هايتي']]],
            ['iso' => 'HM', 'emoji' => '🇭🇲', 'names' => [['locale' => 'en', 'value' => 'Heard Island and McDonald Islands'], ['locale' => 'ar', 'value' => 'جزيرة هيرد وجزر ماكدونالد']]],
            ['iso' => 'HN', 'emoji' => '🇭🇳', 'names' => [['locale' => 'en', 'value' => 'Honduras'], ['locale' => 'ar', 'value' => 'هندوراس']]],
            ['iso' => 'HK', 'emoji' => '🇭🇰', 'names' => [['locale' => 'en', 'value' => 'Hong Kong'], ['locale' => 'ar', 'value' => 'هونغ كونغ']]],
            ['iso' => 'HU', 'emoji' => '🇭🇺', 'names' => [['locale' => 'en', 'value' => 'Hungary'], ['locale' => 'ar', 'value' => 'المجر']]],
            ['iso' => 'IS', 'emoji' => '🇮🇸', 'names' => [['locale' => 'en', 'value' => 'Iceland'], ['locale' => 'ar', 'value' => 'آيسلندا']]],
            ['iso' => 'IN', 'emoji' => '🇮🇳', 'names' => [['locale' => 'en', 'value' => 'India'], ['locale' => 'ar', 'value' => 'الهند']]],
            ['iso' => 'ID', 'emoji' => '🇮🇩', 'names' => [['locale' => 'en', 'value' => 'Indonesia'], ['locale' => 'ar', 'value' => 'إندونيسيا']]],
            ['iso' => 'IR', 'emoji' => '🇮🇷', 'names' => [['locale' => 'en', 'value' => 'Iran'], ['locale' => 'ar', 'value' => 'إيران']]],
            ['iso' => 'IQ', 'emoji' => '🇮🇶', 'names' => [['locale' => 'en', 'value' => 'Iraq'], ['locale' => 'ar', 'value' => 'العراق']]],
            ['iso' => 'IE', 'emoji' => '🇮🇪', 'names' => [['locale' => 'en', 'value' => 'Ireland'], ['locale' => 'ar', 'value' => 'أيرلندا']]],
            ['iso' => 'IM', 'emoji' => '🇮🇲', 'names' => [['locale' => 'en', 'value' => 'Isle of Man'], ['locale' => 'ar', 'value' => 'جزيرة مان']]],
            ['iso' => 'IL', 'emoji' => '🇮🇱', 'names' => [['locale' => 'en', 'value' => 'Israel'], ['locale' => 'ar', 'value' => 'إسرائيل']]],
            ['iso' => 'IT', 'emoji' => '🇮🇹', 'names' => [['locale' => 'en', 'value' => 'Italy'], ['locale' => 'ar', 'value' => 'إيطاليا']]],
            ['iso' => 'CI', 'emoji' => '🇨🇮', 'names' => [['locale' => 'en', 'value' => 'Ivory Coast'], ['locale' => 'ar', 'value' => 'ساحل العاج']]],
            ['iso' => 'JM', 'emoji' => '🇯🇲', 'names' => [['locale' => 'en', 'value' => 'Jamaica'], ['locale' => 'ar', 'value' => 'جامايكا']]],
            ['iso' => 'JP', 'emoji' => '🇯🇵', 'names' => [['locale' => 'en', 'value' => 'Japan'], ['locale' => 'ar', 'value' => 'اليابان']]],
            ['iso' => 'JE', 'emoji' => '🇯🇪', 'names' => [['locale' => 'en', 'value' => 'Jersey'], ['locale' => 'ar', 'value' => 'جزيرة جيرسي']]],
            ['iso' => 'JO', 'emoji' => '🇯🇴', 'names' => [['locale' => 'en', 'value' => 'Jordan'], ['locale' => 'ar', 'value' => 'الأردن']]],
            ['iso' => 'KZ', 'emoji' => '🇰🇿', 'names' => [['locale' => 'en', 'value' => 'Kazakhstan'], ['locale' => 'ar', 'value' => 'كازاخستان']]],
            ['iso' => 'KE', 'emoji' => '🇰🇪', 'names' => [['locale' => 'en', 'value' => 'Kenya'], ['locale' => 'ar', 'value' => 'كينيا']]],
            ['iso' => 'KI', 'emoji' => '🇰🇮', 'names' => [['locale' => 'en', 'value' => 'Kiribati'], ['locale' => 'ar', 'value' => 'كيريباتي']]],
            ['iso' => 'XK', 'emoji' => '🇽🇰', 'names' => [['locale' => 'en', 'value' => 'Kosovo'], ['locale' => 'ar', 'value' => 'كوسوفو']]],
            ['iso' => 'KW', 'emoji' => '🇰🇼', 'names' => [['locale' => 'en', 'value' => 'Kuwait'], ['locale' => 'ar', 'value' => 'الكويت']]],
            ['iso' => 'KG', 'emoji' => '🇰🇬', 'names' => [['locale' => 'en', 'value' => 'Kyrgyzstan'], ['locale' => 'ar', 'value' => 'قيرغيزستان']]],
            ['iso' => 'LA', 'emoji' => '🇱🇦', 'names' => [['locale' => 'en', 'value' => 'Laos'], ['locale' => 'ar', 'value' => 'لاوس']]],
            ['iso' => 'LV', 'emoji' => '🇱🇻', 'names' => [['locale' => 'en', 'value' => 'Latvia'], ['locale' => 'ar', 'value' => 'لاتفيا']]],
            ['iso' => 'LB', 'emoji' => '🇱🇧', 'names' => [['locale' => 'en', 'value' => 'Lebanon'], ['locale' => 'ar', 'value' => 'لبنان']]],
            ['iso' => 'LS', 'emoji' => '🇱🇸', 'names' => [['locale' => 'en', 'value' => 'Lesotho'], ['locale' => 'ar', 'value' => 'ليسوتو']]],
            ['iso' => 'LR', 'emoji' => '🇱🇷', 'names' => [['locale' => 'en', 'value' => 'Liberia'], ['locale' => 'ar', 'value' => 'ليبيريا']]],
            ['iso' => 'LY', 'emoji' => '🇱🇾', 'names' => [['locale' => 'en', 'value' => 'Libya'], ['locale' => 'ar', 'value' => 'ليبيا']]],
            ['iso' => 'LI', 'emoji' => '🇱🇮', 'names' => [['locale' => 'en', 'value' => 'Liechtenstein'], ['locale' => 'ar', 'value' => 'ليختنشتاين']]],
            ['iso' => 'LT', 'emoji' => '🇱🇹', 'names' => [['locale' => 'en', 'value' => 'Lithuania'], ['locale' => 'ar', 'value' => 'ليتوانيا']]],
            ['iso' => 'LU', 'emoji' => '🇱🇺', 'names' => [['locale' => 'en', 'value' => 'Luxembourg'], ['locale' => 'ar', 'value' => 'لوكسمبرغ']]],
            ['iso' => 'MO', 'emoji' => '🇲🇴', 'names' => [['locale' => 'en', 'value' => 'Macao'], ['locale' => 'ar', 'value' => 'ماكاو']]],
            ['iso' => 'MG', 'emoji' => '🇲🇬', 'names' => [['locale' => 'en', 'value' => 'Madagascar'], ['locale' => 'ar', 'value' => 'مدغشقر']]],
            ['iso' => 'MW', 'emoji' => '🇲🇼', 'names' => [['locale' => 'en', 'value' => 'Malawi'], ['locale' => 'ar', 'value' => 'ملاوي']]],
            ['iso' => 'MY', 'emoji' => '🇲🇾', 'names' => [['locale' => 'en', 'value' => 'Malaysia'], ['locale' => 'ar', 'value' => 'ماليزيا']]],
            ['iso' => 'MV', 'emoji' => '🇲🇻', 'names' => [['locale' => 'en', 'value' => 'Maldives'], ['locale' => 'ar', 'value' => 'جزر المالديف']]],
            ['iso' => 'ML', 'emoji' => '🇲🇱', 'names' => [['locale' => 'en', 'value' => 'Mali'], ['locale' => 'ar', 'value' => 'مالي']]],
            ['iso' => 'MT', 'emoji' => '🇲🇹', 'names' => [['locale' => 'en', 'value' => 'Malta'], ['locale' => 'ar', 'value' => 'مالطا']]],
            ['iso' => 'MH', 'emoji' => '🇲🇭', 'names' => [['locale' => 'en', 'value' => 'Marshall Islands'], ['locale' => 'ar', 'value' => 'جزر مارشال']]],
            ['iso' => 'MQ', 'emoji' => '🇲🇶', 'names' => [['locale' => 'en', 'value' => 'Martinique'], ['locale' => 'ar', 'value' => 'مارتينيك']]],
            ['iso' => 'MR', 'emoji' => '🇲🇷', 'names' => [['locale' => 'en', 'value' => 'Mauritania'], ['locale' => 'ar', 'value' => 'موريتانيا']]],
            ['iso' => 'MU', 'emoji' => '🇲🇺', 'names' => [['locale' => 'en', 'value' => 'Mauritius'], ['locale' => 'ar', 'value' => 'موريشيوس']]],
            ['iso' => 'YT', 'emoji' => '🇾🇹', 'names' => [['locale' => 'en', 'value' => 'Mayotte'], ['locale' => 'ar', 'value' => 'مايوت']]],
            ['iso' => 'MX', 'emoji' => '🇲🇽', 'names' => [['locale' => 'en', 'value' => 'Mexico'], ['locale' => 'ar', 'value' => 'المكسيك']]],
            ['iso' => 'FM', 'emoji' => '🇫🇲', 'names' => [['locale' => 'en', 'value' => 'Micronesia'], ['locale' => 'ar', 'value' => 'ميكرونيسيا']]],
            ['iso' => 'MD', 'emoji' => '🇲🇩', 'names' => [['locale' => 'en', 'value' => 'Moldova'], ['locale' => 'ar', 'value' => 'مولدوفا']]],
            ['iso' => 'MC', 'emoji' => '🇲🇨', 'names' => [['locale' => 'en', 'value' => 'Monaco'], ['locale' => 'ar', 'value' => 'موناكو']]],
            ['iso' => 'MN', 'emoji' => '🇲🇳', 'names' => [['locale' => 'en', 'value' => 'Mongolia'], ['locale' => 'ar', 'value' => 'منغوليا']]],
            ['iso' => 'ME', 'emoji' => '🇲🇪', 'names' => [['locale' => 'en', 'value' => 'Montenegro'], ['locale' => 'ar', 'value' => 'الجبل الأسود']]],
            ['iso' => 'MA', 'emoji' => '🇲🇦', 'names' => [['locale' => 'en', 'value' => 'Morocco'], ['locale' => 'ar', 'value' => 'المغرب']]],
            ['iso' => 'MZ', 'emoji' => '🇲🇿', 'names' => [['locale' => 'en', 'value' => 'Mozambique'], ['locale' => 'ar', 'value' => 'موزمبيق']]],
            ['iso' => 'MM', 'emoji' => '🇲🇲', 'names' => [['locale' => 'en', 'value' => 'Myanmar'], ['locale' => 'ar', 'value' => 'ميانمار']]],
            ['iso' => 'NA', 'emoji' => '🇳🇦', 'names' => [['locale' => 'en', 'value' => 'Namibia'], ['locale' => 'ar', 'value' => 'ناميبيا']]],
            ['iso' => 'NR', 'emoji' => '🇳🇷', 'names' => [['locale' => 'en', 'value' => 'Nauru'], ['locale' => 'ar', 'value' => 'ناورو']]],
            ['iso' => 'NP', 'emoji' => '🇳🇵', 'names' => [['locale' => 'en', 'value' => 'Nepal'], ['locale' => 'ar', 'value' => 'نيبال']]],
            ['iso' => 'NL', 'emoji' => '🇳🇱', 'names' => [['locale' => 'en', 'value' => 'Netherlands'], ['locale' => 'ar', 'value' => 'هولندا']]],
            ['iso' => 'AN', 'emoji' => '🇦🇳', 'names' => [['locale' => 'en', 'value' => 'Netherlands Antilles'], ['locale' => 'ar', 'value' => 'جزر الأنتيل الهولندية']]],
            ['iso' => 'NC', 'emoji' => '🇳🇨', 'names' => [['locale' => 'en', 'value' => 'New Caledonia'], ['locale' => 'ar', 'value' => 'كاليدونيا الجديدة']]],
            ['iso' => 'NZ', 'emoji' => '🇳🇿', 'names' => [['locale' => 'en', 'value' => 'New Zealand'], ['locale' => 'ar', 'value' => 'نيوزيلندا']]],
            ['iso' => 'NI', 'emoji' => '🇳🇮', 'names' => [['locale' => 'en', 'value' => 'Nicaragua'], ['locale' => 'ar', 'value' => 'نيكاراغوا']]],
            ['iso' => 'NE', 'emoji' => '🇳🇪', 'names' => [['locale' => 'en', 'value' => 'Niger'], ['locale' => 'ar', 'value' => 'النيجر']]],
            ['iso' => 'NG', 'emoji' => '🇳🇬', 'names' => [['locale' => 'en', 'value' => 'Nigeria'], ['locale' => 'ar', 'value' => 'نيجيريا']]],
            ['iso' => 'NU', 'emoji' => '🇳🇺', 'names' => [['locale' => 'en', 'value' => 'Niue'], ['locale' => 'ar', 'value' => 'نيوي']]],
            ['iso' => 'NF', 'emoji' => '🇳🇫', 'names' => [['locale' => 'en', 'value' => 'Norfolk Island'], ['locale' => 'ar', 'value' => 'جزيرة نورفولك']]],
            ['iso' => 'KP', 'emoji' => '🇰🇵', 'names' => [['locale' => 'en', 'value' => 'North Korea'], ['locale' => 'ar', 'value' => 'كوريا الشمالية']]],
            ['iso' => 'MK', 'emoji' => '🇲🇰', 'names' => [['locale' => 'en', 'value' => 'North Macedonia'], ['locale' => 'ar', 'value' => 'مقدونيا الشمالية']]],
            ['iso' => 'MP', 'emoji' => '🇲🇵', 'names' => [['locale' => 'en', 'value' => 'Northern Mariana Islands'], ['locale' => 'ar', 'value' => 'جزر ماريانا الشمالية']]],
            ['iso' => 'NO', 'emoji' => '🇳🇴', 'names' => [['locale' => 'en', 'value' => 'Norway'], ['locale' => 'ar', 'value' => 'النرويج']]],
            ['iso' => 'OM', 'emoji' => '🇴🇲', 'names' => [['locale' => 'en', 'value' => 'Oman'], ['locale' => 'ar', 'value' => 'عمان']]],
            ['iso' => 'PK', 'emoji' => '🇵🇰', 'names' => [['locale' => 'en', 'value' => 'Pakistan'], ['locale' => 'ar', 'value' => 'باكستان']]],
            ['iso' => 'PW', 'emoji' => '🇵🇼', 'names' => [['locale' => 'en', 'value' => 'Palau'], ['locale' => 'ar', 'value' => 'بالاو']]],
            ['iso' => 'PS', 'emoji' => '🇵🇸', 'names' => [['locale' => 'en', 'value' => 'Palestine'], ['locale' => 'ar', 'value' => 'فلسطين']]],
            ['iso' => 'PA', 'emoji' => '🇵🇦', 'names' => [['locale' => 'en', 'value' => 'Panama'], ['locale' => 'ar', 'value' => 'بنما']]],
            ['iso' => 'PG', 'emoji' => '🇵🇬', 'names' => [['locale' => 'en', 'value' => 'Papua New Guinea'], ['locale' => 'ar', 'value' => 'بابوا غينيا الجديدة']]],
            ['iso' => 'PY', 'emoji' => '🇵🇾', 'names' => [['locale' => 'en', 'value' => 'Paraguay'], ['locale' => 'ar', 'value' => 'باراغواي']]],
            ['iso' => 'PE', 'emoji' => '🇵🇪', 'names' => [['locale' => 'en', 'value' => 'Peru'], ['locale' => 'ar', 'value' => 'بيرو']]],
            ['iso' => 'PH', 'emoji' => '🇵🇭', 'names' => [['locale' => 'en', 'value' => 'Philippines'], ['locale' => 'ar', 'value' => 'الفلبين']]],
            ['iso' => 'PN', 'emoji' => '🇵🇳', 'names' => [['locale' => 'en', 'value' => 'Pitcairn Islands'], ['locale' => 'ar', 'value' => 'جزر بيتكيرن']]],
            ['iso' => 'PL', 'emoji' => '🇵🇱', 'names' => [['locale' => 'en', 'value' => 'Poland'], ['locale' => 'ar', 'value' => 'بولندا']]],
            ['iso' => 'PT', 'emoji' => '🇵🇹', 'names' => [['locale' => 'en', 'value' => 'Portugal'], ['locale' => 'ar', 'value' => 'البرتغال']]],
            ['iso' => 'PR', 'emoji' => '��🇷', 'names' => [['locale' => 'en', 'value' => 'Puerto Rico'], ['locale' => 'ar', 'value' => 'بورتوريكو']]],
            ['iso' => 'QA', 'emoji' => '🇶🇦', 'names' => [['locale' => 'en', 'value' => 'Qatar'], ['locale' => 'ar', 'value' => 'قطر']]],
            ['iso' => 'RE', 'emoji' => '🇷🇪', 'names' => [['locale' => 'en', 'value' => 'Reunion'], ['locale' => 'ar', 'value' => 'ريونيون']]],
            ['iso' => 'RO', 'emoji' => '🇷🇴', 'names' => [['locale' => 'en', 'value' => 'Romania'], ['locale' => 'ar', 'value' => 'رومانيا']]],
            ['iso' => 'RU', 'emoji' => '🇷🇺', 'names' => [['locale' => 'en', 'value' => 'Russia'], ['locale' => 'ar', 'value' => 'روسيا']]],
            ['iso' => 'RW', 'emoji' => '🇷🇼', 'names' => [['locale' => 'en', 'value' => 'Rwanda'], ['locale' => 'ar', 'value' => 'رواندا']]],
            ['iso' => 'KN', 'emoji' => '🇰🇳', 'names' => [['locale' => 'en', 'value' => 'Saint Kitts and Nevis'], ['locale' => 'ar', 'value' => 'سانت كيتس ونيفس']]],
            ['iso' => 'LC', 'emoji' => '🇱🇨', 'names' => [['locale' => 'en', 'value' => 'Saint Lucia'], ['locale' => 'ar', 'value' => 'سانت لوسيا']]],
            ['iso' => 'PM', 'emoji' => '🇵🇲', 'names' => [['locale' => 'en', 'value' => 'Saint Martin'], ['locale' => 'ar', 'value' => 'سانت مارتن']]],
            ['iso' => 'VC', 'emoji' => '🇻🇨', 'names' => [['locale' => 'en', 'value' => 'Saint Vincent and the Grenadines'], ['locale' => 'ar', 'value' => 'سانت فنسنت وجزر غرينادين']]],
            ['iso' => 'WS', 'emoji' => '🇼🇸', 'names' => [['locale' => 'en', 'value' => 'Samoa'], ['locale' => 'ar', 'value' => 'ساموا']]],
            ['iso' => 'SM', 'emoji' => '🇸🇲', 'names' => [['locale' => 'en', 'value' => 'San Marino'], ['locale' => 'ar', 'value' => 'سان مارينو']]],
            ['iso' => 'ST', 'emoji' => '🇸🇹', 'names' => [['locale' => 'en', 'value' => 'Sao Tome and Principe'], ['locale' => 'ar', 'value' => 'سان تومي وبرينسيبي']]],
            ['iso' => 'SA', 'emoji' => '🇸🇦', 'names' => [['locale' => 'en', 'value' => 'Saudi Arabia'], ['locale' => 'ar', 'value' => 'المملكة العربية السعودية']]],
            ['iso' => 'SN', 'emoji' => '🇸🇳', 'names' => [['locale' => 'en', 'value' => 'Senegal'], ['locale' => 'ar', 'value' => 'السنغال']]],
            ['iso' => 'RS', 'emoji' => '🇷🇸', 'names' => [['locale' => 'en', 'value' => 'Serbia'], ['locale' => 'ar', 'value' => 'صربيا']]],
            ['iso' => 'SC', 'emoji' => '🇸🇨', 'names' => [['locale' => 'en', 'value' => 'Seychelles'], ['locale' => 'ar', 'value' => 'سيشل']]],
            ['iso' => 'SL', 'emoji' => '🇸🇱', 'names' => [['locale' => 'en', 'value' => 'Sierra Leone'], ['locale' => 'ar', 'value' => 'سيراليون']]],
            ['iso' => 'SG', 'emoji' => '🇸🇬', 'names' => [['locale' => 'en', 'value' => 'Singapore'], ['locale' => 'ar', 'value' => 'سنغافورة']]],
            ['iso' => 'SK', 'emoji' => '🇸🇰', 'names' => [['locale' => 'en', 'value' => 'Slovakia'], ['locale' => 'ar', 'value' => 'سلوفاكيا']]],
            ['iso' => 'SI', 'emoji' => '🇸🇮', 'names' => [['locale' => 'en', 'value' => 'Slovenia'], ['locale' => 'ar', 'value' => 'سلوفينيا']]],
            ['iso' => 'SB', 'emoji' => '🇸🇧', 'names' => [['locale' => 'en', 'value' => 'Solomon Islands'], ['locale' => 'ar', 'value' => 'جزر سليمان']]],
            ['iso' => 'SO', 'emoji' => '🇸🇴', 'names' => [['locale' => 'en', 'value' => 'Somalia'], ['locale' => 'ar', 'value' => 'الصومال']]],
            ['iso' => 'ZA', 'emoji' => '🇿🇦', 'names' => [['locale' => 'en', 'value' => 'South Africa'], ['locale' => 'ar', 'value' => 'جنوب أفريقيا']]],
            ['iso' => 'GS', 'emoji' => '🇬🇸', 'names' => [['locale' => 'en', 'value' => 'South Georgia and the South Sandwich Islands'], ['locale' => 'ar', 'value' => 'جزيرة جنوب جورجيا وجزر ساندويتش الجنوبية']]],
            ['iso' => 'KR', 'emoji' => '🇰🇷', 'names' => [['locale' => 'en', 'value' => 'South Korea'], ['locale' => 'ar', 'value' => 'كوريا الجنوبية']]],
            ['iso' => 'SS', 'emoji' => '🇸🇸', 'names' => [['locale' => 'en', 'value' => 'South Sudan'], ['locale' => 'ar', 'value' => 'جنوب السودان']]],
            ['iso' => 'ES', 'emoji' => '🇪🇸', 'names' => [['locale' => 'en', 'value' => 'Spain'], ['locale' => 'ar', 'value' => 'إسبانيا']]],
            ['iso' => 'LK', 'emoji' => '🇱🇰', 'names' => [['locale' => 'en', 'value' => 'Sri Lanka'], ['locale' => 'ar', 'value' => 'سريلانكا']]],
            ['iso' => 'SD', 'emoji' => '🇸🇩', 'names' => [['locale' => 'en', 'value' => 'Sudan'], ['locale' => 'ar', 'value' => 'السودان']]],
            ['iso' => 'SR', 'emoji' => '🇸🇷', 'names' => [['locale' => 'en', 'value' => 'Suriname'], ['locale' => 'ar', 'value' => 'سورينام']]],
            ['iso' => 'SJ', 'emoji' => '🇸🇯', 'names' => [['locale' => 'en', 'value' => 'Svalbard and Jan Mayen'], ['locale' => 'ar', 'value' => 'سفالبار وجان مايان']]],
            ['iso' => 'SZ', 'emoji' => '🇸🇿', 'names' => [['locale' => 'en', 'value' => 'Eswatini'], ['locale' => 'ar', 'value' => 'إسواتيني']]],
            ['iso' => 'SE', 'emoji' => '🇸🇪', 'names' => [['locale' => 'en', 'value' => 'Sweden'], ['locale' => 'ar', 'value' => 'السويد']]],
            ['iso' => 'CH', 'emoji' => '🇨🇭', 'names' => [['locale' => 'en', 'value' => 'Switzerland'], ['locale' => 'ar', 'value' => 'سويسرا']]],
            ['iso' => 'SY', 'emoji' => '🇸🇾', 'names' => [['locale' => 'en', 'value' => 'Syria'], ['locale' => 'ar', 'value' => 'سوريا']]],
            ['iso' => 'TW', 'emoji' => '🇹🇼', 'names' => [['locale' => 'en', 'value' => 'Taiwan'], ['locale' => 'ar', 'value' => 'تايوان']]],
            ['iso' => 'TJ', 'emoji' => '��🇯', 'names' => [['locale' => 'en', 'value' => 'Tajikistan'], ['locale' => 'ar', 'value' => 'طاجيكستان']]],
            ['iso' => 'TZ', 'emoji' => '🇹🇿', 'names' => [['locale' => 'en', 'value' => 'Tanzania'], ['locale' => 'ar', 'value' => 'تنزانيا']]],
            ['iso' => 'TH', 'emoji' => '🇹🇭', 'names' => [['locale' => 'en', 'value' => 'Thailand'], ['locale' => 'ar', 'value' => 'تايلاند']]],
            ['iso' => 'TL', 'emoji' => '🇹🇱', 'names' => [['locale' => 'en', 'value' => 'Timor-Leste'], ['locale' => 'ar', 'value' => 'تيمور الشرقية']]],
            ['iso' => 'TG', 'emoji' => '🇹🇬', 'names' => [['locale' => 'en', 'value' => 'Togo'], ['locale' => 'ar', 'value' => 'توغو']]],
            ['iso' => 'TK', 'emoji' => '🇹🇰', 'names' => [['locale' => 'en', 'value' => 'Tokelau'], ['locale' => 'ar', 'value' => 'توكيلاو']]],
            ['iso' => 'TO', 'emoji' => '🇹🇴', 'names' => [['locale' => 'en', 'value' => 'Tonga'], ['locale' => 'ar', 'value' => 'تونغا']]],
            ['iso' => 'TT', 'emoji' => '🇹��', 'names' => [['locale' => 'en', 'value' => 'Trinidad and Tobago'], ['locale' => 'ar', 'value' => 'ترينيداد وتوباغو']]],
            ['iso' => 'TN', 'emoji' => '🇹🇳', 'names' => [['locale' => 'en', 'value' => 'Tunisia'], ['locale' => 'ar', 'value' => 'تونس']]],
            ['iso' => 'TR', 'emoji' => '🇹🇷', 'names' => [['locale' => 'en', 'value' => 'Turkey'], ['locale' => 'ar', 'value' => 'تركيا']]],
            ['iso' => 'TM', 'emoji' => '🇹🇲', 'names' => [['locale' => 'en', 'value' => 'Turkmenistan'], ['locale' => 'ar', 'value' => 'تركمانستان']]],
            ['iso' => 'TC', 'emoji' => '🇹🇨', 'names' => [['locale' => 'en', 'value' => 'Turks and Caicos Islands'], ['locale' => 'ar', 'value' => 'جزر تركس وكايكوس']]],
            ['iso' => 'TV', 'emoji' => '🇹🇻', 'names' => [['locale' => 'en', 'value' => 'Tuvalu'], ['locale' => 'ar', 'value' => 'توفالو']]],
            ['iso' => 'UG', 'emoji' => '🇺🇬', 'names' => [['locale' => 'en', 'value' => 'Uganda'], ['locale' => 'ar', 'value' => 'أوغندا']]],
            ['iso' => 'UA', 'emoji' => '🇺🇦', 'names' => [['locale' => 'en', 'value' => 'Ukraine'], ['locale' => 'ar', 'value' => 'أوكرانيا']]],
            ['iso' => 'AE', 'emoji' => '🇦🇪', 'names' => [['locale' => 'en', 'value' => 'United Arab Emirates'], ['locale' => 'ar', 'value' => 'الإمارات العربية المتحدة']]],
            ['iso' => 'GB', 'emoji' => '🇬🇧', 'names' => [['locale' => 'en', 'value' => 'United Kingdom'], ['locale' => 'ar', 'value' => 'المملكة المتحدة']]],
            ['iso' => 'US', 'emoji' => '🇺🇸', 'names' => [['locale' => 'en', 'value' => 'United States'], ['locale' => 'ar', 'value' => 'الولايات المتحدة']]],
            ['iso' => 'UY', 'emoji' => '🇺🇾', 'names' => [['locale' => 'en', 'value' => 'Uruguay'], ['locale' => 'ar', 'value' => 'أوروغواي']]],
            ['iso' => 'UZ', 'emoji' => '🇺🇿', 'names' => [['locale' => 'en', 'value' => 'Uzbekistan'], ['locale' => 'ar', 'value' => 'أوزبكستان']]],
            ['iso' => 'VU', 'emoji' => '🇻🇺', 'names' => [['locale' => 'en', 'value' => 'Vanuatu'], ['locale' => 'ar', 'value' => 'فانواتو']]],
            ['iso' => 'VA', 'emoji' => '🇻🇦', 'names' => [['locale' => 'en', 'value' => 'Vatican City'], ['locale' => 'ar', 'value' => 'الفاتيكان']]],
            ['iso' => 'VE', 'emoji' => '🇻🇪', 'names' => [['locale' => 'en', 'value' => 'Venezuela'], ['locale' => 'ar', 'value' => 'فنزويلا']]],
            ['iso' => 'VN', 'emoji' => '🇻🇳', 'names' => [['locale' => 'en', 'value' => 'Vietnam'], ['locale' => 'ar', 'value' => 'فيتنام']]],
            ['iso' => 'VG', 'emoji' => '🇻🇬', 'names' => [['locale' => 'en', 'value' => 'British Virgin Islands'], ['locale' => 'ar', 'value' => 'جزر العذراء البريطانية']]],
            ['iso' => 'VI', 'emoji' => '🇻🇮', 'names' => [['locale' => 'en', 'value' => 'US Virgin Islands'], ['locale' => 'ar', 'value' => 'جزر العذراء الأمريكية']]],
            ['iso' => 'WF', 'emoji' => '🇼🇫', 'names' => [['locale' => 'en', 'value' => 'Wallis and Futuna'], ['locale' => 'ar', 'value' => 'واليس وفوتونا']]],
            ['iso' => 'EH', 'emoji' => '🇪🇭', 'names' => [['locale' => 'en', 'value' => 'Western Sahara'], ['locale' => 'ar', 'value' => 'الصحراء الغربية']]],
            ['iso' => 'YE', 'emoji' => '🇾🇪', 'names' => [['locale' => 'en', 'value' => 'Yemen'], ['locale' => 'ar', 'value' => 'اليمن']]],
            ['iso' => 'ZM', 'emoji' => '🇿🇲', 'names' => [['locale' => 'en', 'value' => 'Zambia'], ['locale' => 'ar', 'value' => 'زامبيا']]],
            ['iso' => 'ZW', 'emoji' => '🇿🇼', 'names' => [['locale' => 'en', 'value' => 'Zimbabwe'], ['locale' => 'ar', 'value' => 'زيمبابوي']]],
        ];

        foreach ($countries as $country) {
            Country::create([
                'id' => (string) Str::ulid(),
                'iso_code' => $country['iso'],
                'emoji_flag' => $country['emoji'],
                'name_translations' => $country['names'],
            ]);
        }
    }
}
