<?php

namespace Modules\Geo\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Geo\Models\Currency;
use Illuminate\Support\Str;

class CurrenciesSeeder extends Seeder
{
    /**
     * Run the database seeds - All major world currencies
     */
    public function run(): void
    {
        $currencies = [
            ['code' => 'AED', 'symbol' => 'د.إ', 'names' => [['locale' => 'en', 'value' => 'UAE Dirham'], ['locale' => 'ar', 'value' => 'درهم إماراتي']], 'decimals' => 2],
            ['code' => 'AFN', 'symbol' => '؋', 'names' => [['locale' => 'en', 'value' => 'Afghan Afghani'], ['locale' => 'ar', 'value' => 'أفغاني أفغاني']], 'decimals' => 2],
            ['code' => 'ALL', 'symbol' => 'L', 'names' => [['locale' => 'en', 'value' => 'Albanian Lek'], ['locale' => 'ar', 'value' => 'ليك ألباني']], 'decimals' => 2],
            ['code' => 'AMD', 'symbol' => '֏', 'names' => [['locale' => 'en', 'value' => 'Armenian Dram'], ['locale' => 'ar', 'value' => 'درام أرميني']], 'decimals' => 2],
            ['code' => 'ANG', 'symbol' => 'ƒ', 'names' => [['locale' => 'en', 'value' => 'Netherlands Antillean Guilder'], ['locale' => 'ar', 'value' => 'غيلدر جزر الأنتيل']], 'decimals' => 2],
            ['code' => 'AOA', 'symbol' => 'Kz', 'names' => [['locale' => 'en', 'value' => 'Angolan Kwanza'], ['locale' => 'ar', 'value' => 'كوانزا أنغولي']], 'decimals' => 2],
            ['code' => 'ARS', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Argentine Peso'], ['locale' => 'ar', 'value' => 'بيزو أرجنتيني']], 'decimals' => 2],
            ['code' => 'AUD', 'symbol' => 'A$', 'names' => [['locale' => 'en', 'value' => 'Australian Dollar'], ['locale' => 'ar', 'value' => 'دولار أسترالي']], 'decimals' => 2],
            ['code' => 'AWG', 'symbol' => 'ƒ', 'names' => [['locale' => 'en', 'value' => 'Aruban Florin'], ['locale' => 'ar', 'value' => 'فلورين أروبي']], 'decimals' => 2],
            ['code' => 'AZN', 'symbol' => '₼', 'names' => [['locale' => 'en', 'value' => 'Azerbaijani Manat'], ['locale' => 'ar', 'value' => 'منات أذربيجاني']], 'decimals' => 2],
            ['code' => 'BAM', 'symbol' => 'KM', 'names' => [['locale' => 'en', 'value' => 'Bosnia-Herzegovina Convertible Mark'], ['locale' => 'ar', 'value' => 'مارك بوسني قابل للتحويل']], 'decimals' => 2],
            ['code' => 'BBD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Barbadian Dollar'], ['locale' => 'ar', 'value' => 'دولار باربادوسي']], 'decimals' => 2],
            ['code' => 'BDT', 'symbol' => '৳', 'names' => [['locale' => 'en', 'value' => 'Bangladeshi Taka'], ['locale' => 'ar', 'value' => 'تاكا بنغلاديشية']], 'decimals' => 2],
            ['code' => 'BGN', 'symbol' => 'лв', 'names' => [['locale' => 'en', 'value' => 'Bulgarian Lev'], ['locale' => 'ar', 'value' => 'ليف بلغاري']], 'decimals' => 2],
            ['code' => 'BHD', 'symbol' => '.د.ب', 'names' => [['locale' => 'en', 'value' => 'Bahraini Dinar'], ['locale' => 'ar', 'value' => 'دينار بحريني']], 'decimals' => 3],
            ['code' => 'BIF', 'symbol' => 'FBu', 'names' => [['locale' => 'en', 'value' => 'Burundian Franc'], ['locale' => 'ar', 'value' => 'فرنك بوروندي']], 'decimals' => 0],
            ['code' => 'BMD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Bermudian Dollar'], ['locale' => 'ar', 'value' => 'دولار برمودي']], 'decimals' => 2],
            ['code' => 'BND', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Brunei Dollar'], ['locale' => 'ar', 'value' => 'دولار بروناي']], 'decimals' => 2],
            ['code' => 'BOB', 'symbol' => 'Bs.', 'names' => [['locale' => 'en', 'value' => 'Bolivian Boliviano'], ['locale' => 'ar', 'value' => 'بوليفيانو بوليفي']], 'decimals' => 2],
            ['code' => 'BRL', 'symbol' => 'R$', 'names' => [['locale' => 'en', 'value' => 'Brazilian Real'], ['locale' => 'ar', 'value' => 'ريال برازيلي']], 'decimals' => 2],
            ['code' => 'BSD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Bahamian Dollar'], ['locale' => 'ar', 'value' => 'دولار باهامي']], 'decimals' => 2],
            ['code' => 'BTC', 'symbol' => '₿', 'names' => [['locale' => 'en', 'value' => 'Bitcoin'], ['locale' => 'ar', 'value' => 'بيتكوين']], 'decimals' => 8],
            ['code' => 'BTN', 'symbol' => 'Nu.', 'names' => [['locale' => 'en', 'value' => 'Bhutanese Ngultrum'], ['locale' => 'ar', 'value' => 'نجولترم بوتاني']], 'decimals' => 2],
            ['code' => 'BWP', 'symbol' => 'P', 'names' => [['locale' => 'en', 'value' => 'Botswanan Pula'], ['locale' => 'ar', 'value' => 'بولا بوتسواني']], 'decimals' => 2],
            ['code' => 'BYN', 'symbol' => 'Br', 'names' => [['locale' => 'en', 'value' => 'Belarusian Ruble'], ['locale' => 'ar', 'value' => 'روبل بيلاروسي']], 'decimals' => 2],
            ['code' => 'BZD', 'symbol' => 'BZ$', 'names' => [['locale' => 'en', 'value' => 'Belizean Dollar'], ['locale' => 'ar', 'value' => 'دولار بليزي']], 'decimals' => 2],
            ['code' => 'CAD', 'symbol' => 'C$', 'names' => [['locale' => 'en', 'value' => 'Canadian Dollar'], ['locale' => 'ar', 'value' => 'دولار كندي']], 'decimals' => 2],
            ['code' => 'CDF', 'symbol' => 'FC', 'names' => [['locale' => 'en', 'value' => 'Congolese Franc'], ['locale' => 'ar', 'value' => 'فرنك كونغولي']], 'decimals' => 2],
            ['code' => 'CHF', 'symbol' => 'CHF', 'names' => [['locale' => 'en', 'value' => 'Swiss Franc'], ['locale' => 'ar', 'value' => 'فرنك سويسري']], 'decimals' => 2],
            ['code' => 'CLF', 'symbol' => 'UF', 'names' => [['locale' => 'en', 'value' => 'Chilean Unit of Account'], ['locale' => 'ar', 'value' => 'وحدة حساب تشيلية']], 'decimals' => 4],
            ['code' => 'CLP', 'symbol' => 'CLP', 'names' => [['locale' => 'en', 'value' => 'Chilean Peso'], ['locale' => 'ar', 'value' => 'بيزو تشيلي']], 'decimals' => 0],
            ['code' => 'CNH', 'symbol' => 'CNH', 'names' => [['locale' => 'en', 'value' => 'Chinese Yuan (Offshore)'], ['locale' => 'ar', 'value' => 'يوان صيني (خارج الجزيرة)']], 'decimals' => 2],
            ['code' => 'CNY', 'symbol' => '¥', 'names' => [['locale' => 'en', 'value' => 'Chinese Yuan'], ['locale' => 'ar', 'value' => 'يوان صيني']], 'decimals' => 2],
            ['code' => 'COP', 'symbol' => 'CO$', 'names' => [['locale' => 'en', 'value' => 'Colombian Peso'], ['locale' => 'ar', 'value' => 'بيزو كولومبي']], 'decimals' => 2],
            ['code' => 'CRC', 'symbol' => '₡', 'names' => [['locale' => 'en', 'value' => 'Costa Rican Colón'], ['locale' => 'ar', 'value' => 'كولون كوستاريكي']], 'decimals' => 2],
            ['code' => 'CUC', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Cuban Convertible Peso'], ['locale' => 'ar', 'value' => 'بيزو كوبي قابل للتحويل']], 'decimals' => 2],
            ['code' => 'CUP', 'symbol' => '₱', 'names' => [['locale' => 'en', 'value' => 'Cuban Peso'], ['locale' => 'ar', 'value' => 'بيزو كوبي']], 'decimals' => 2],
            ['code' => 'CVE', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Cape Verdean Escudo'], ['locale' => 'ar', 'value' => 'إسكودو القيرط']], 'decimals' => 2],
            ['code' => 'CZK', 'symbol' => 'Kč', 'names' => [['locale' => 'en', 'value' => 'Czech Koruna'], ['locale' => 'ar', 'value' => 'كورونا تشيكية']], 'decimals' => 2],
            ['code' => 'DJF', 'symbol' => 'Fdj', 'names' => [['locale' => 'en', 'value' => 'Djiboutian Franc'], ['locale' => 'ar', 'value' => 'فرنك جيبوتي']], 'decimals' => 0],
            ['code' => 'DKK', 'symbol' => 'kr', 'names' => [['locale' => 'en', 'value' => 'Danish Krone'], ['locale' => 'ar', 'value' => 'كرون دنماركي']], 'decimals' => 2],
            ['code' => 'DOP', 'symbol' => 'RD$', 'names' => [['locale' => 'en', 'value' => 'Dominican Peso'], ['locale' => 'ar', 'value' => 'بيزو دومينيكاني']], 'decimals' => 2],
            ['code' => 'DZD', 'symbol' => 'د.ج', 'names' => [['locale' => 'en', 'value' => 'Algerian Dinar'], ['locale' => 'ar', 'value' => 'دينار جزائري']], 'decimals' => 2],
            ['code' => 'EGP', 'symbol' => 'ج.م', 'names' => [['locale' => 'en', 'value' => 'Egyptian Pound'], ['locale' => 'ar', 'value' => 'جنيه مصري']], 'decimals' => 2],
            ['code' => 'ERN', 'symbol' => 'Nfk', 'names' => [['locale' => 'en', 'value' => 'Eritrean Nakfa'], ['locale' => 'ar', 'value' => 'نقفة إريترية']], 'decimals' => 2],
            ['code' => 'ETB', 'symbol' => 'Br', 'names' => [['locale' => 'en', 'value' => 'Ethiopian Birr'], ['locale' => 'ar', 'value' => 'بير إثيوبي']], 'decimals' => 2],
            ['code' => 'EUR', 'symbol' => '€', 'names' => [['locale' => 'en', 'value' => 'Euro'], ['locale' => 'ar', 'value' => 'يورو']], 'decimals' => 2],
            ['code' => 'FJD', 'symbol' => 'FJ$', 'names' => [['locale' => 'en', 'value' => 'Fijian Dollar'], ['locale' => 'ar', 'value' => 'دولار فيجي']], 'decimals' => 2],
            ['code' => 'FKP', 'symbol' => '£', 'names' => [['locale' => 'en', 'value' => 'Falkland Pound'], ['locale' => 'ar', 'value' => 'جنيه فوكلاند']], 'decimals' => 2],
            ['code' => 'GBP', 'symbol' => '£', 'names' => [['locale' => 'en', 'value' => 'British Pound'], ['locale' => 'ar', 'value' => 'جنيه إسترليني']], 'decimals' => 2],
            ['code' => 'GEL', 'symbol' => '₾', 'names' => [['locale' => 'en', 'value' => 'Georgian Lari'], ['locale' => 'ar', 'value' => 'لاري جورجي']], 'decimals' => 2],
            ['code' => 'GHS', 'symbol' => '₵', 'names' => [['locale' => 'en', 'value' => 'Ghanaian Cedi'], ['locale' => 'ar', 'value' => 'سيدي غاني']], 'decimals' => 2],
            ['code' => 'GIP', 'symbol' => '£', 'names' => [['locale' => 'en', 'value' => 'Gibraltar Pound'], ['locale' => 'ar', 'value' => 'جنيه جبل طارق']], 'decimals' => 2],
            ['code' => 'GMD', 'symbol' => 'D', 'names' => [['locale' => 'en', 'value' => 'Gambian Dalasi'], ['locale' => 'ar', 'value' => 'دالاسي غامبي']], 'decimals' => 2],
            ['code' => 'GNF', 'symbol' => 'FG', 'names' => [['locale' => 'en', 'value' => 'Guinean Franc'], ['locale' => 'ar', 'value' => 'فرنك غيني']], 'decimals' => 0],
            ['code' => 'GTQ', 'symbol' => 'Q', 'names' => [['locale' => 'en', 'value' => 'Guatemalan Quetzal'], ['locale' => 'ar', 'value' => 'كيتزال جواتيمالي']], 'decimals' => 2],
            ['code' => 'GYD', 'symbol' => 'G$', 'names' => [['locale' => 'en', 'value' => 'Guyanaese Dollar'], ['locale' => 'ar', 'value' => 'دولار غياني']], 'decimals' => 2],
            ['code' => 'HKD', 'symbol' => 'HK$', 'names' => [['locale' => 'en', 'value' => 'Hong Kong Dollar'], ['locale' => 'ar', 'value' => 'دولار هونج كونج']], 'decimals' => 2],
            ['code' => 'HNL', 'symbol' => 'L', 'names' => [['locale' => 'en', 'value' => 'Honduran Lempira'], ['locale' => 'ar', 'value' => 'ليمبيرا هندوراسي']], 'decimals' => 2],
            ['code' => 'HRK', 'symbol' => 'kn', 'names' => [['locale' => 'en', 'value' => 'Croatian Kuna'], ['locale' => 'ar', 'value' => 'كونا كرواتية']], 'decimals' => 2],
            ['code' => 'HTG', 'symbol' => 'G', 'names' => [['locale' => 'en', 'value' => 'Haitian Gourde'], ['locale' => 'ar', 'value' => 'قرد هايتي']], 'decimals' => 2],
            ['code' => 'HUF', 'symbol' => 'Ft', 'names' => [['locale' => 'en', 'value' => 'Hungarian Forint'], ['locale' => 'ar', 'value' => 'فورنت مجري']], 'decimals' => 2],
            ['code' => 'IDR', 'symbol' => 'Rp', 'names' => [['locale' => 'en', 'value' => 'Indonesian Rupiah'], ['locale' => 'ar', 'value' => 'روبية إندونيسية']], 'decimals' => 2],
            ['code' => 'ILS', 'symbol' => '₪', 'names' => [['locale' => 'en', 'value' => 'Israeli Shekel'], ['locale' => 'ar', 'value' => 'شيكل إسرائيلي']], 'decimals' => 2],
            ['code' => 'INR', 'symbol' => '₹', 'names' => [['locale' => 'en', 'value' => 'Indian Rupee'], ['locale' => 'ar', 'value' => 'روبية هندية']], 'decimals' => 2],
            ['code' => 'IQD', 'symbol' => 'د.ع', 'names' => [['locale' => 'en', 'value' => 'Iraqi Dinar'], ['locale' => 'ar', 'value' => 'دينار عراقي']], 'decimals' => 3],
            ['code' => 'IRR', 'symbol' => '﷼', 'names' => [['locale' => 'en', 'value' => 'Iranian Rial'], ['locale' => 'ar', 'value' => 'ريال إيراني']], 'decimals' => 2],
            ['code' => 'ISK', 'symbol' => 'kr', 'names' => [['locale' => 'en', 'value' => 'Icelandic Króna'], ['locale' => 'ar', 'value' => 'كرونة آيسلندية']], 'decimals' => 0],
            ['code' => 'JMD', 'symbol' => 'J$', 'names' => [['locale' => 'en', 'value' => 'Jamaican Dollar'], ['locale' => 'ar', 'value' => 'دولار جامايكي']], 'decimals' => 2],
            ['code' => 'JOD', 'symbol' => 'د.ا', 'names' => [['locale' => 'en', 'value' => 'Jordanian Dinar'], ['locale' => 'ar', 'value' => 'دينار أردني']], 'decimals' => 3],
            ['code' => 'JPY', 'symbol' => '¥', 'names' => [['locale' => 'en', 'value' => 'Japanese Yen'], ['locale' => 'ar', 'value' => 'ين ياباني']], 'decimals' => 0],
            ['code' => 'KES', 'symbol' => 'KSh', 'names' => [['locale' => 'en', 'value' => 'Kenyan Shilling'], ['locale' => 'ar', 'value' => 'شلن كيني']], 'decimals' => 2],
            ['code' => 'KGS', 'symbol' => 'с', 'names' => [['locale' => 'en', 'value' => 'Kyrgyzstani Som'], ['locale' => 'ar', 'value' => 'سوم قيرغيزي']], 'decimals' => 2],
            ['code' => 'KHR', 'symbol' => '៛', 'names' => [['locale' => 'en', 'value' => 'Cambodian Riel'], ['locale' => 'ar', 'value' => 'ريال كمبودي']], 'decimals' => 2],
            ['code' => 'KMF', 'symbol' => 'CF', 'names' => [['locale' => 'en', 'value' => 'Comorian Franc'], ['locale' => 'ar', 'value' => 'فرنك جزر القمر']], 'decimals' => 0],
            ['code' => 'KPW', 'symbol' => '₩', 'names' => [['locale' => 'en', 'value' => 'North Korean Won'], ['locale' => 'ar', 'value' => 'وون كوري شمالي']], 'decimals' => 2],
            ['code' => 'KRW', 'symbol' => '₩', 'names' => [['locale' => 'en', 'value' => 'South Korean Won'], ['locale' => 'ar', 'value' => 'وون كوري جنوبي']], 'decimals' => 0],
            ['code' => 'KWD', 'symbol' => 'د.ك', 'names' => [['locale' => 'en', 'value' => 'Kuwaiti Dinar'], ['locale' => 'ar', 'value' => 'دينار كويتي']], 'decimals' => 3],
            ['code' => 'KYD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Cayman Dollar'], ['locale' => 'ar', 'value' => 'دولار جزر كايمان']], 'decimals' => 2],
            ['code' => 'KZT', 'symbol' => '₸', 'names' => [['locale' => 'en', 'value' => 'Kazakhstani Tenge'], ['locale' => 'ar', 'value' => 'تنغي كازاخستاني']], 'decimals' => 2],
            ['code' => 'LAK', 'symbol' => '₭', 'names' => [['locale' => 'en', 'value' => 'Laotian Kip'], ['locale' => 'ar', 'value' => 'كيب لاوسي']], 'decimals' => 2],
            ['code' => 'LBP', 'symbol' => 'ل.ل', 'names' => [['locale' => 'en', 'value' => 'Lebanese Pound'], ['locale' => 'ar', 'value' => 'جنيه لبناني']], 'decimals' => 2],
            ['code' => 'LKR', 'symbol' => 'Rs', 'names' => [['locale' => 'en', 'value' => 'Sri Lankan Rupee'], ['locale' => 'ar', 'value' => 'روبية سريلانكية']], 'decimals' => 2],
            ['code' => 'LRD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Liberian Dollar'], ['locale' => 'ar', 'value' => 'دولار ليبيري']], 'decimals' => 2],
            ['code' => 'LSL', 'symbol' => 'L', 'names' => [['locale' => 'en', 'value' => 'Lesotho Loti'], ['locale' => 'ar', 'value' => 'لوتي ليسوتو']], 'decimals' => 2],
            ['code' => 'LYD', 'symbol' => 'ل.د', 'names' => [['locale' => 'en', 'value' => 'Libyan Dinar'], ['locale' => 'ar', 'value' => 'دينار ليبي']], 'decimals' => 3],
            ['code' => 'MAD', 'symbol' => 'د.م.', 'names' => [['locale' => 'en', 'value' => 'Moroccan Dirham'], ['locale' => 'ar', 'value' => 'درهم مغربي']], 'decimals' => 2],
            ['code' => 'MDL', 'symbol' => 'L', 'names' => [['locale' => 'en', 'value' => 'Moldovan Leu'], ['locale' => 'ar', 'value' => 'ليو مولدافي']], 'decimals' => 2],
            ['code' => 'MGA', 'symbol' => 'Ar', 'names' => [['locale' => 'en', 'value' => 'Malagasy Ariary'], ['locale' => 'ar', 'value' => 'أرياري ملغاسي']], 'decimals' => 2],
            ['code' => 'MKD', 'symbol' => 'ден', 'names' => [['locale' => 'en', 'value' => 'Macedonian Denar'], ['locale' => 'ar', 'value' => 'دينار مقدوني']], 'decimals' => 2],
            ['code' => 'MMK', 'symbol' => 'Ks', 'names' => [['locale' => 'en', 'value' => 'Myanmar Kyat'], ['locale' => 'ar', 'value' => 'كيات ميانماري']], 'decimals' => 2],
            ['code' => 'MNT', 'symbol' => '₮', 'names' => [['locale' => 'en', 'value' => 'Mongolian Tugrik'], ['locale' => 'ar', 'value' => 'توغريك منغولي']], 'decimals' => 2],
            ['code' => 'MOP', 'symbol' => 'P', 'names' => [['locale' => 'en', 'value' => 'Macanese Pataca'], ['locale' => 'ar', 'value' => 'باتاكا ماكاوية']], 'decimals' => 2],
            ['code' => 'MRU', 'symbol' => 'UM', 'names' => [['locale' => 'en', 'value' => 'Mauritanian Ouguiya'], ['locale' => 'ar', 'value' => 'أوقية موريتانية']], 'decimals' => 2],
            ['code' => 'MUR', 'symbol' => '₨', 'names' => [['locale' => 'en', 'value' => 'Mauritian Rupee'], ['locale' => 'ar', 'value' => 'روبية موريشية']], 'decimals' => 2],
            ['code' => 'MVR', 'symbol' => 'Rf', 'names' => [['locale' => 'en', 'value' => 'Maldivian Rufiyaa'], ['locale' => 'ar', 'value' => 'روفية مالديفية']], 'decimals' => 2],
            ['code' => 'MWK', 'symbol' => 'MK', 'names' => [['locale' => 'en', 'value' => 'Malawian Kwacha'], ['locale' => 'ar', 'value' => 'كواشا ملاوية']], 'decimals' => 2],
            ['code' => 'MXN', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Mexican Peso'], ['locale' => 'ar', 'value' => 'بيزو مكسيكي']], 'decimals' => 2],
            ['code' => 'MYR', 'symbol' => 'RM', 'names' => [['locale' => 'en', 'value' => 'Malaysian Ringgit'], ['locale' => 'ar', 'value' => 'رنجت ماليزي']], 'decimals' => 2],
            ['code' => 'MZN', 'symbol' => 'MT', 'names' => [['locale' => 'en', 'value' => 'Mozambican Metical'], ['locale' => 'ar', 'value' => 'متيكال موزمبيقي']], 'decimals' => 2],
            ['code' => 'NAD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Namibian Dollar'], ['locale' => 'ar', 'value' => 'دولار ناميبي']], 'decimals' => 2],
            ['code' => 'NGN', 'symbol' => '₦', 'names' => [['locale' => 'en', 'value' => 'Nigerian Naira'], ['locale' => 'ar', 'value' => 'نيرة نيجيرية']], 'decimals' => 2],
            ['code' => 'NIO', 'symbol' => 'C$', 'names' => [['locale' => 'en', 'value' => 'Nicaraguan Córdoba'], ['locale' => 'ar', 'value' => 'قرطبة نيكاراغوية']], 'decimals' => 2],
            ['code' => 'NOK', 'symbol' => 'kr', 'names' => [['locale' => 'en', 'value' => 'Norwegian Krone'], ['locale' => 'ar', 'value' => 'كرون نرويجي']], 'decimals' => 2],
            ['code' => 'NPR', 'symbol' => '₨', 'names' => [['locale' => 'en', 'value' => 'Nepalese Rupee'], ['locale' => 'ar', 'value' => 'روبية نيبالية']], 'decimals' => 2],
            ['code' => 'NZD', 'symbol' => 'NZ$', 'names' => [['locale' => 'en', 'value' => 'New Zealand Dollar'], ['locale' => 'ar', 'value' => 'دولار نيوزيلندي']], 'decimals' => 2],
            ['code' => 'OMR', 'symbol' => 'ر.ع.', 'names' => [['locale' => 'en', 'value' => 'Omani Rial'], ['locale' => 'ar', 'value' => 'ريال عماني']], 'decimals' => 3],
            ['code' => 'PAB', 'symbol' => 'B/.', 'names' => [['locale' => 'en', 'value' => 'Panamanian Balboa'], ['locale' => 'ar', 'value' => 'بالبوا بنمي']], 'decimals' => 2],
            ['code' => 'PEN', 'symbol' => 'S/.', 'names' => [['locale' => 'en', 'value' => 'Peruvian Sol'], ['locale' => 'ar', 'value' => 'سول بيروفي']], 'decimals' => 2],
            ['code' => 'PGK', 'symbol' => 'K', 'names' => [['locale' => 'en', 'value' => 'Papua New Guinean Kina'], ['locale' => 'ar', 'value' => 'كينا بابوا غينيا الجديدة']], 'decimals' => 2],
            ['code' => 'PHP', 'symbol' => '₱', 'names' => [['locale' => 'en', 'value' => 'Philippine Peso'], ['locale' => 'ar', 'value' => 'بيزو فلبيني']], 'decimals' => 2],
            ['code' => 'PKR', 'symbol' => '₨', 'names' => [['locale' => 'en', 'value' => 'Pakistani Rupee'], ['locale' => 'ar', 'value' => 'روبية باكستانية']], 'decimals' => 2],
            ['code' => 'PLN', 'symbol' => 'zł', 'names' => [['locale' => 'en', 'value' => 'Polish Zloty'], ['locale' => 'ar', 'value' => 'زلوتي بولندي']], 'decimals' => 2],
            ['code' => 'PYG', 'symbol' => '₲', 'names' => [['locale' => 'en', 'value' => 'Paraguayan Guarani'], ['locale' => 'ar', 'value' => 'غواراني باراغوايي']], 'decimals' => 0],
            ['code' => 'QAR', 'symbol' => 'ر.ق', 'names' => [['locale' => 'en', 'value' => 'Qatari Riyal'], ['locale' => 'ar', 'value' => 'ريال قطري']], 'decimals' => 2],
            ['code' => 'RON', 'symbol' => 'lei', 'names' => [['locale' => 'en', 'value' => 'Romanian Leu'], ['locale' => 'ar', 'value' => 'ليو روماني']], 'decimals' => 2],
            ['code' => 'RSD', 'symbol' => 'Дин.', 'names' => [['locale' => 'en', 'value' => 'Serbian Dinar'], ['locale' => 'ar', 'value' => 'دينار صربي']], 'decimals' => 2],
            ['code' => 'RUB', 'symbol' => '₽', 'names' => [['locale' => 'en', 'value' => 'Russian Ruble'], ['locale' => 'ar', 'value' => 'روبل روسي']], 'decimals' => 2],
            ['code' => 'RWF', 'symbol' => 'FRw', 'names' => [['locale' => 'en', 'value' => 'Rwandan Franc'], ['locale' => 'ar', 'value' => 'فرنك رواندي']], 'decimals' => 0],
            ['code' => 'SAR', 'symbol' => 'ر.س', 'names' => [['locale' => 'en', 'value' => 'Saudi Riyal'], ['locale' => 'ar', 'value' => 'ريال سعودي']], 'decimals' => 2],
            ['code' => 'SBD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Solomon Islands Dollar'], ['locale' => 'ar', 'value' => 'دولار جزر سليمان']], 'decimals' => 2],
            ['code' => 'SCR', 'symbol' => '₨', 'names' => [['locale' => 'en', 'value' => 'Seychellois Rupee'], ['locale' => 'ar', 'value' => 'روبية سيشيلية']], 'decimals' => 2],
            ['code' => 'SDG', 'symbol' => 'ج.س', 'names' => [['locale' => 'en', 'value' => 'Sudanese Pound'], ['locale' => 'ar', 'value' => 'جنيه سوداني']], 'decimals' => 2],
            ['code' => 'SEK', 'symbol' => 'kr', 'names' => [['locale' => 'en', 'value' => 'Swedish Krona'], ['locale' => 'ar', 'value' => 'كرونة سويدية']], 'decimals' => 2],
            ['code' => 'SGD', 'symbol' => 'S$', 'names' => [['locale' => 'en', 'value' => 'Singapore Dollar'], ['locale' => 'ar', 'value' => 'دولار سنغافوري']], 'decimals' => 2],
            ['code' => 'SHP', 'symbol' => '£', 'names' => [['locale' => 'en', 'value' => 'St. Helena Pound'], ['locale' => 'ar', 'value' => 'جنيه سانت هيلينا']], 'decimals' => 2],
            ['code' => 'SLL', 'symbol' => 'Le', 'names' => [['locale' => 'en', 'value' => 'Sierra Leonean Leone'], ['locale' => 'ar', 'value' => 'ليون سيراليوني']], 'decimals' => 2],
            ['code' => 'SOS', 'symbol' => 'Sh', 'names' => [['locale' => 'en', 'value' => 'Somali Shilling'], ['locale' => 'ar', 'value' => 'شلن صومالي']], 'decimals' => 2],
            ['code' => 'SRD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Surinamese Dollar'], ['locale' => 'ar', 'value' => 'دولار سوريناميسي']], 'decimals' => 2],
            ['code' => 'SSP', 'symbol' => '£', 'names' => [['locale' => 'en', 'value' => 'South Sudanese Pound'], ['locale' => 'ar', 'value' => 'جنيه جنوب السودان']], 'decimals' => 2],
            ['code' => 'STN', 'symbol' => 'Db', 'names' => [['locale' => 'en', 'value' => 'São Tomé & Príncipe Dobra'], ['locale' => 'ar', 'value' => 'دوبرا سانت تومي وبرينسيبي']], 'decimals' => 2],
            ['code' => 'SYP', 'symbol' => 'ل.س', 'names' => [['locale' => 'en', 'value' => 'Syrian Pound'], ['locale' => 'ar', 'value' => 'جنيه سوري']], 'decimals' => 2],
            ['code' => 'SZL', 'symbol' => 'L', 'names' => [['locale' => 'en', 'value' => 'Swazi Lilangeni'], ['locale' => 'ar', 'value' => 'ليلانجيني إسواتيني']], 'decimals' => 2],
            ['code' => 'THB', 'symbol' => '฿', 'names' => [['locale' => 'en', 'value' => 'Thai Baht'], ['locale' => 'ar', 'value' => 'بات تايلاندي']], 'decimals' => 2],
            ['code' => 'TJS', 'symbol' => 'ЅМ', 'names' => [['locale' => 'en', 'value' => 'Tajikistani Somoni'], ['locale' => 'ar', 'value' => 'سوموني طاجيكي']], 'decimals' => 2],
            ['code' => 'TMT', 'symbol' => 'm', 'names' => [['locale' => 'en', 'value' => 'Turkmenistani Manat'], ['locale' => 'ar', 'value' => 'منات تركمني']], 'decimals' => 2],
            ['code' => 'TND', 'symbol' => 'د.ت', 'names' => [['locale' => 'en', 'value' => 'Tunisian Dinar'], ['locale' => 'ar', 'value' => 'دينار تونسي']], 'decimals' => 3],
            ['code' => 'TOP', 'symbol' => 'T$', 'names' => [['locale' => 'en', 'value' => 'Tongan Paʻanga'], ['locale' => 'ar', 'value' => 'پاآنگا تونغي']], 'decimals' => 2],
            ['code' => 'TRY', 'symbol' => '₺', 'names' => [['locale' => 'en', 'value' => 'Turkish Lira'], ['locale' => 'ar', 'value' => 'ليرة تركية']], 'decimals' => 2],
            ['code' => 'TTD', 'symbol' => 'TT$', 'names' => [['locale' => 'en', 'value' => 'Trinidad & Tobago Dollar'], ['locale' => 'ar', 'value' => 'دولار ترينيداد وتوباغو']], 'decimals' => 2],
            ['code' => 'TWD', 'symbol' => 'NT$', 'names' => [['locale' => 'en', 'value' => 'Taiwan Dollar'], ['locale' => 'ar', 'value' => 'دولار تايواني']], 'decimals' => 2],
            ['code' => 'TZS', 'symbol' => 'TSh', 'names' => [['locale' => 'en', 'value' => 'Tanzanian Shilling'], ['locale' => 'ar', 'value' => 'شلن تنزاني']], 'decimals' => 2],
            ['code' => 'UAH', 'symbol' => '₴', 'names' => [['locale' => 'en', 'value' => 'Ukrainian Hryvnia'], ['locale' => 'ar', 'value' => 'هريفنيا أوكرانية']], 'decimals' => 2],
            ['code' => 'UGX', 'symbol' => 'USh', 'names' => [['locale' => 'en', 'value' => 'Ugandan Shilling'], ['locale' => 'ar', 'value' => 'شلن أوغندي']], 'decimals' => 0],
            ['code' => 'USD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'US Dollar'], ['locale' => 'ar', 'value' => 'دولار أمريكي']], 'decimals' => 2],
            ['code' => 'UYU', 'symbol' => '$U', 'names' => [['locale' => 'en', 'value' => 'Uruguayan Peso'], ['locale' => 'ar', 'value' => 'بيزو أوروغوايي']], 'decimals' => 2],
            ['code' => 'UZS', 'symbol' => 'сўм', 'names' => [['locale' => 'en', 'value' => 'Uzbekistani Som'], ['locale' => 'ar', 'value' => 'سوم أوزبكي']], 'decimals' => 2],
            ['code' => 'VES', 'symbol' => 'Bs.', 'names' => [['locale' => 'en', 'value' => 'Venezuelan Bolívar'], ['locale' => 'ar', 'value' => 'بوليفار فنزويلي']], 'decimals' => 2],
            ['code' => 'VND', 'symbol' => '₫', 'names' => [['locale' => 'en', 'value' => 'Vietnamese Dong'], ['locale' => 'ar', 'value' => 'دونج فيتنامي']], 'decimals' => 0],
            ['code' => 'VUV', 'symbol' => 'Vt', 'names' => [['locale' => 'en', 'value' => 'Vanuatu Vatu'], ['locale' => 'ar', 'value' => 'فاتو فانواتو']], 'decimals' => 0],
            ['code' => 'WST', 'symbol' => 'T', 'names' => [['locale' => 'en', 'value' => 'Samoan Tālā'], ['locale' => 'ar', 'value' => 'تالا ساموي']], 'decimals' => 2],
            ['code' => 'XAF', 'symbol' => 'FCFA', 'names' => [['locale' => 'en', 'value' => 'CFA Franc BEAC'], ['locale' => 'ar', 'value' => 'فرنك CFA BEAC']], 'decimals' => 0],
            ['code' => 'XCD', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'East Caribbean Dollar'], ['locale' => 'ar', 'value' => 'دولار شرق الكاريبي']], 'decimals' => 2],
            ['code' => 'XOF', 'symbol' => 'CFA', 'names' => [['locale' => 'en', 'value' => 'CFA Franc WAEMU'], ['locale' => 'ar', 'value' => 'فرنك CFA WAEMU']], 'decimals' => 0],
            ['code' => 'XPF', 'symbol' => '₣', 'names' => [['locale' => 'en', 'value' => 'CFP Franc'], ['locale' => 'ar', 'value' => 'فرنك CFP']], 'decimals' => 0],
            ['code' => 'YER', 'symbol' => '﷼', 'names' => [['locale' => 'en', 'value' => 'Yemeni Rial'], ['locale' => 'ar', 'value' => 'ريال يمني']], 'decimals' => 2],
            ['code' => 'ZAR', 'symbol' => 'R', 'names' => [['locale' => 'en', 'value' => 'South African Rand'], ['locale' => 'ar', 'value' => 'راند جنوب أفريقي']], 'decimals' => 2],
            ['code' => 'ZMW', 'symbol' => 'ZK', 'names' => [['locale' => 'en', 'value' => 'Zambian Kwacha'], ['locale' => 'ar', 'value' => 'كواشا زامبية']], 'decimals' => 2],
            ['code' => 'ZWL', 'symbol' => '$', 'names' => [['locale' => 'en', 'value' => 'Zimbabwe Dollar'], ['locale' => 'ar', 'value' => 'دولار زيمبابوي']], 'decimals' => 2],
        ];

        foreach ($currencies as $currency) {
            Currency::create([
                'id' => (string) Str::ulid(),
                'code' => $currency['code'],
                'symbol' => $currency['symbol'],
                'name_translations' => $currency['names'],
                'decimal_places' => $currency['decimals'],
            ]);
        }
    }
}
